### ISSUE TITLE
Adapt sys command according to feedback.

### ISSUE THREAD

**Issue by busykoala** [busykoala/flask-login-gibb#11]
We are unsure what the command should look like.

Options we could think of are:
- `ls -hal <substitute>`
- `ls <substitute> <substitute>`

**Comment by BitPatty** [comment]
Suggestion: `a`, `c`, `h`, `l`, `s`, `t`, maybe `X`, others tbd + prevent user from moving out of the projects location

I guess we should ask BD first what exactly he's expecting

**Comment by BitPatty** [comment]
7a2f5388b45d11ab8b904735aeead95630f1449a
