### ISSUE TITLE
Persistent and save pw storage.

### ISSUE THREAD

**Issue by busykoala** [busykoala/flask-login-gibb#5]
Sichere persistente Passwortspeicherung, gegen Wörterbuch-Angriffe.

**Comment by busykoala** [comment]
@BitPatty, ich denke mit Salt zusammen gehashed in die DB ist wohl zufriedenstellend, was meinst du?

**Comment by BitPatty** [comment]
yes sir

vorzugsweise sha-512 oder bcrypt

**Comment by busykoala** [comment]
Es ist sha 512 implementiert.

`self.password_hash = generate_password_hash(salted_pw, method='pbkdf2:sha512')`
